[platformio]
description = sortingmachine
default_envs = nanoatmega328new

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    Servo
    arduino-libraries/Stepper@^1.1.3

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328new

[env:nanoatmega168]
platform = atmelavr
board = nanoatmega168

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new

[env:uno]
platform = atmelavr
board = uno